# This is the overal configs of the test group
["Configs"]
units = ["_host", "client"]
debug-modes = ["DEBUG", "INFO", "WARNING", "EXCEPT"]
test-modes = ["DEBUG"]                               # Can be "<MODE>", ["<MODE1>", <"MODE2">, ...], "All"
use-ai = false
diagnostics = true
detect-bad-behavior = true
save-resume = true
repeat = 0                                           # can be any between 0 - 10
analitics = true
save-analitics = true
save-performance = true